theisel/astro-portabletext

astro-portabletext/docs/extending-components.md
Remove import `astro-portabletext/types` in preference of defining type
=> docs(astro-portabletext/docs): extending-components.md

package.json, pnpm-lock.yaml
- `eslint-plugin-prettier` rolled back to v4
- `prettier-plugin-svelte` rolled back to v2
=> chore(prettier): fix formatting error

.github/workflows/npm.yml
Remove --filter flag to fix "Cannot install with 'frozen-lockfile'" error
=> chore(workflow/npm): fix `install deps` step

astro-portabletext/package.json, demo/package.json
Bump versions as 216ed544 had no effect on creating a new release
- Bump `astro-portabletext` version
- Bump `demo` version
- Lockfile was fixed in d7b68707 following release
=> fix(release): fix bad release

.husky/post-merge
Script has no effect as it was dropped from the `astro-portabletext` package
=> chore(husky): remove `compile` script

.github/workflows/test.yml
Astro no longer supports Node v16
=> ci(workflow/test): drop Node v16

astro-portabletext/lib/types.ts, astro-portabletext/package.json, pnpm-lock.yaml
Update dependencies to latest versions
- @portabletext/toolkit
- @portabletext/types
Fix #92 
- Fix `mark` and `unknownMark` types
=> fix(astro-portabletext): update dependencies and fix #92

.github/workflows/format.yml, .github/workflows/npm.yml, .github/workflows/release.yml, .github/workflows/test.yml
Upgrade actions
- actions/checkout to v4
- pnpm/action-setup to v3
- actions/setup-node to v4
- stefanzweifel/git-auto-commit-action to v5
- google-github-actions/release-please-action to v4
Upgrade Node version
- Set version to v20
=> ci: fix actions

astro-portabletext/components/PortableText.astro, astro-portabletext/docs/types.md, astro-portabletext/lib/types.ts
Remove `class` prop and don't pass it to the render components as it's unpredictable
BREAKING CHANGE: use `scoped` and `global` styles instead
refactor(types)!: drop `class` from `Props` as it's outside of scope
BREAKING CHANGE: extend `Props` to accept `class`
=> refactor(component)!: drop `class` prop from `PortableText`

demo/.codesandbox/Dockerfile, demo/.devcontainer/devcontainer.json, demo/.stackblitzrc, demo/package.json, demo/src/components/FancyBorder.astro, demo/src/components/ListItemStyleStar.astro, demo/src/components/ListStyleStar.astro, demo/src/components/counter/Counter.astro, demo/src/components/counter/JsxCounter.astro, demo/src/components/counter/SvelteCounter.astro, demo/src/components/counter/index.ts, demo/src/components/portabletext/Block.astro, demo/src/components/portabletext/List.astro, demo/src/components/portabletext/Mark.astro, demo/src/components/portabletext/PortableText.astro, demo/src/components/portabletext/Type.astro, demo/src/data/portabletext.json, demo/src/layouts/Default.astro, demo/src/pages/index.astro, pnpm-lock.yaml
Features
- Added `Counter` component
- Added `link` mark definition to portable text data
Fixes
- Updated dependencies to latest version
- Fixed types
- Fixed `Stackblitz` config
- Update `CodeSandbox` Node version
Refactored
- Components and styles
=> feat: add component, add mark definition to portabletext, including fixes and refactoring

.release-please-manifest.json, release-please-config.json
Update `release-please` configuration and manifest. Separate `demo` versioning isn't needed.
=> refactor: drop `demo` package versioning

astro-portabletext/package.json, pnpm-lock.yaml
Prevent double spaces in `toPlainText` output (see https://github.com/portabletext/toolkit/pull/93).
=> fix(deps): bump @portabletext/toolkit to v2.0.16

release-please-config.json
Updates the `last-release-sha` in the release-please configuration to reflect the recent manual release, ensuring accurate release tracking.
=> chore(release): update last-release-sha to reflect manual release

astro-portabletext/README.md, astro-portabletext/components/PortableText.astro, astro-portabletext/components/Text.astro, astro-portabletext/lib/types.ts, lab/src/components/TextReplace.astro, lab/src/components/TextStyleBySplit.astro, lab/src/components/TextStylebyIndex.astro, lab/src/pages/text/default.astro, lab/src/pages/text/replace.astro, lab/src/pages/text/style-by-index.astro, lab/src/pages/text/style-by-split.astro, lab/src/pages/text/undefined.astro, lab/src/test/text.test.js
Provides users with fine-grained control over text node output via the new `text` option.
```ts
// pages/some-page.astro
---
import { PortableText } from "astro-portabletext";
import TextReplace from '@/components/TextReplace.astro';
---
<PortableText value={/* Portable Text blocks */} components={{text: TextReplace}}/>
```
```ts
// TextReplace.astro
---
import type { TextNode, Props as $ } from "astro-portabletext/types";
export type Props = $<TextNode>;
const { node } = Astro.props;
const replacedText = node.text.replace('panda', '🐼');
---
{replacedText}
```
=> feat(component): enable custom text rendering in PortableText

.github/workflows/test.yml
Adds Node v22 to the test workflow to ensure compatibility with the latest Astro requirements
=> ci: add Node v22 to test workflow

astro-portabletext/docs/types/README.md, astro-portabletext/docs/types/type-aliases/BlockProps.md, astro-portabletext/docs/types/type-aliases/ListItemProps.md, astro-portabletext/docs/types/type-aliases/ListProps.md, astro-portabletext/docs/types/type-aliases/MarkProps.md, astro-portabletext/docs/types/type-aliases/TextNodeProps.md, astro-portabletext/lib/types.ts
Added type aliases for component props to simplify user imports and improve type readability. The type aliases include: `BlockProps`, `ListProps`, `ListItemProps`, `MarkProps<MarkDef>`, and `TextNodeProps`.
```diff
- import type { Props as $, Block } from "astro-portabletext/types";
+ import type { BlockProps } from "astro-portabletext/types";
- type Props = $<Block>;
+ type Props = BlockProps;
```
=> feat(api): simplify component prop imports with type aliases

README.md
Hey,
This addresses my confusion in #173.
I'm sure there's a better way to do this that won't require editing the README on release. Maybe using a git tag or something?
But anyway, I think this is an improvement that would already help for now, so users don't end up on the wrong docs.
=> docs(root): update documentation links in readme

astro-portabletext/README.md
Fixed several broken links in the library README. The links were missing the `blob/main` prefix, like in this example:
**Before:** https://github.com/theisel/astro-portabletext/docs/README.md
**After:** https://github.com/theisel/astro-portabletext/blob/main/docs/README.md
This change enhances the README's usability and provides a more reliable source of information for users.
=> docs(library): fix broken links in readme

astro-portabletext/lib/utils.d.ts, astro-portabletext/lib/utils.ts, docs/utility-functions.md
Adds the `spanToPlainText` function to the library's API for extracting text from Portable Text spans (see [https://portabletext.github.io/toolkit/functions/spanToPlainText.html](https://portabletext.github.io/toolkit/functions/spanToPlainText.html)).
```js
import { spanToPlainText } from "astro-portabletext";
```
**Deprecation:** The import path `astro-portabletext/utils` for `spanToPlainText` is deprecated. This utility path will be removed in a future release.
Documentation updated.
Closes #178
=> feat(api): add `spanToPlainText` function (docs updated)

release-please-config.json
Removes the `group-pull-request-title-pattern` from the release configuration in an attempt to resolve issues with the `release-please` action not releasing as expected. Further investigation is needed if the release still fails.
=> chore: remove `group-pull-request-title-pattern` from release config

astro-portabletext/CHANGELOG.md, astro-portabletext/package.json
This change improves the distribution of the npm package by including the CHANGELOG.md file. This provides users with easy access to release notes and helps them understand changes between versions.
Duplicate entries in the CHANGELOG.md file, caused by a previous failed release, have also been removed to ensure accuracy.
=> build(npm): include CHANGELOG and clean up duplicates

release-please-config.json
Release-please is generating unnecessary release notes, possibly due to an incorrect last release SHA.
Updates the last release SHA in the release-please config to the correct value: b59dd9a384340451a332a7fbd1e807f95e5ed8e3.
Release-please should now only generate release notes for actual new releases.
=> chore(release): update last release SHA in release-please config

.release-please-manifest.json
`release-please` failed to update `astro-portabletext` to `0.11.0` in the release manifest.
Manually update `astro-portabletext` to `0.11.0` in `.release-please-manifest.json`.
=> chore(release): update astro-portabletext version to 0.11.0 in release manifest

astro-portabletext/README.md
Truncate "Utility functions" in README for brevity. See docs for details.
=> docs(astro-portabletext): truncate "Utility functions" in README

astro-portabletext/package.json, pnpm-lock.yaml
Fixes error when `markDefs` is null in `buildMarksTree` function. Tested locally.
=> fix(deps): update @portabletext/toolkit v2.0.17

.release-please-manifest.json, release-please-config.json
Manually updates the `release-please-manifest.json` file to v0.11.1. There is an issue with the `release-please` action not updating this file automatically and produces a fresh release PR upon release.
Updates the `last-release-sha` in `release-please-config.json` to reflect the latest release.
=> chore(release): manually update `version` and `last-release-sha` in release-please manifest and config files

release-please-config.json
Sets `separate-pull-requests` explicitly to false. See [googleapis/release-please#2172](https://github.com/googleapis/release-please/issues/2172).
Hopefully this issue is now resolved.
=> chore(release): fix release-please manifest update

docs/utility-functions.md
Added the missing `spanToPlainText` import to the code example and noted its introduction in v0.11.0 within the relevant section.
=> docs(user-guide): add `spanToPlainText` import and v0.11.0 note

astro-portabletext/package.json, pnpm-lock.yaml
This PR updates `@portabletext/toolkit` to its latest patch version `v3.0.1`.
=> fix(deps): bump @portabletext/toolkit to v3.0.1
