astro-portabletext/docs/sanity.md

docs(astro-portabletext/docs): sanity

---

release-please-config.json

chore(release-please): config

---

.github/workflows/test.yml

`Test` should only run on changes to `astro-portabletext` package

ci(workflow/test): fix trigger event

---

.github/workflows/npm.yml

Constrain `pnpm install` to `astro-portabletext` package

ci(workflow/npm): fix `Install Dependencies` step

---

.github/workflows/release.yml

- Added `Publish to NPM` check step to simplify condition checks on following steps
- Fixes step condition test on `actions/checkout` and `Dispatch NPM Workflow`

ci(workflow): release

---

astro-portabletext/docs/hydration.md

Split the document into sections with headings

docs(astro-portabletext/docs): hydration.md

---

astro-portabletext/lib/types.ts

`MarkDef` type to extend Record<string, unknown>

fix(lib/types): interface `Mark`

---

release-please-config.json

- Remove `separate-pull-requests` use default
- Remove `pull-request-title-pattern` use default
- Add `group-pull-request-title-pattern`

chore(release-please): update config

---

astro-portabletext/package.json
pnpm-lock.yaml

`@portabletext/types` has been updated to resolve this issue.
Closes #60

fix(deps): update `astro-portabletext` dependencies

---

.github/workflows/npm.yml

Add missing git user to the workflow

chore(workflow/npm): add `setup user` step

---

.github/workflows/npm.yml

Put `Setup User` as the first step

chore(workflow/npm): change step order

---

.github/workflows/npm.yml

This reverts commit 8f97183fa42bfd1477f712d19eb37d92e65c4ce1.

revert: "chore(workflow/npm): change step order (#76)"

---

.github/workflows/npm.yml
release-please-config.json

- Lockfile was fixed in https://github.com/theisel/astro-portabletext/commit/d7b6870763f5c6c815578d2fdb529a4d2b3ec11b following release

fix(release): create new release

---

.github/workflows/test.yml

Test should trigger on push event

chore(workflow/test): add `release-please` branches

---

.husky/pre-push

Deleting it has no effect as this hook didn't do anything

chore(husky): delete `pre-push` hook

---

package.json
pnpm-lock.yaml

Astro 3 depends on @astrojs/check

chore(deps): add @astrojs/check

---

astro-portabletext/tsconfig.json

Remove duplicate `compilerOptions`
- Drop `strict`
- Drop `forceConsistentCasingInFileNames`
- Drop `verbatimModuleSyntax`

refactor(tsconfig): use `astro/tsconfigs/strict`

---

demo/package.json
demo/src/components/ListItemStyleStar.astro
demo/src/components/ListStyleStar.astro
demo/src/components/counter/Counter.svelte
demo/src/components/counter/Counter.tsx
demo/src/components/counter/JsxCounter.astro
demo/src/components/counter/SvelteCounter.astro
demo/src/components/portabletext/Block.astro
demo/src/components/portabletext/List.astro
demo/src/components/portabletext/ListItem.astro
demo/src/components/portabletext/Mark.astro
demo/src/components/portabletext/Type.astro
pnpm-lock.yaml

- Update dependencies
- Fix components

fix(demo): update `demo` package

---

demo/src/components/portabletext/PortableText.astro

Import declaration conflicts with local declaration of 'PortableText'

fix(demo): fix import declaration

---

demo/src/components/portabletext/PortableText.astro

Fix component name which relates to #e2168b73

fix(demo): fix PortableText is not defined

---

demo/src/pages/index.astro

Add directive to pages/index.astro

fix(demo): add `is:global` directive to style

---

.prettierrc
package.json
pnpm-lock.yaml

- devDependencies
- engines
Fix `prettierrc` plugins path to resolve import error

chore(root): update dependencies

---

.github/workflows/npm.yml

Publish npm package with provenance

ci(npm): add provenance flag

---

demo/.codesandbox/Dockerfile

chore(demo): add `codesandbox` config

---

.github/workflows/format.yml

Add token to `actions/checkout`

ci(format): add token

---

astro-portabletext/lib/types.ts

Fix with `never` type
Closes #92

fix(astro-portabletext): fix #92

---

demo/package.json
pnpm-lock.yaml

fix(demo): update dependencies

---

astro-portabletext/docs/extending-components.md
astro-portabletext/docs/hydration.md
astro-portabletext/docs/sanity.md
astro-portabletext/docs/types.md

- extending-components.md
- hydration.md
- sanity.md
- types.md

docs(astro-portabletext): update docs

---

demo/package.json
pnpm-lock.yaml

fix(deps): update `demo` dependencies

---

package.json
pnpm-lock.yaml

Update `devDependencies` and `engines` to latest versions

chore(deps): update `root` dependencies

---

demo/package.json
pnpm-lock.yaml

Update `dependencies` and `engines` to latest version

feat(deps): update `demo` dependencies

---

astro-portabletext/package.json
pnpm-lock.yaml

Update dependencies to latest version

fix(deps): update `astro-portabletext`

---

astro-portabletext/components/PortableText.astro
lab/src/components/BlockIndex.astro
lab/src/pages/block/block-index.astro
lab/src/test/block.test.js

Block index should be incrementing

fix: block index

---

astro-portabletext/lib/types.ts

fix(types): fix docblock comments

---

release-please-config.json

chore(release-please): override default `changelog-sections`

---

.npmrc
package.json
pnpm-lock.yaml

Use `astro` dependency from `demo` package

chore: hoist `astro` dependency

---

demo/.astro/settings.json
demo/package.json
pnpm-lock.yaml

Update `dependencies` to latest version

fix(demo): update `dependencies`

---

release-please-config.json

Hides documentation changes from release notes

chore(release): hide documentation changes

---

lab/package.json
lab/src/components/issues/BlockStandFirst.astro
lab/src/pages/issues/issue-175.astro
lab/src/test/issue.test.js
pnpm-lock.yaml

Verifies that the duplicate list item issue (#175) has been resolved. This issue appears to have been fixed as a side effect of recent changes to the library's rendering logic.

test: verify #175 (duplicate list items) is resolved by recent changes

---

examples/Text.astro

Fixes https://github.com/theisel/astro-portabletext/issues/190

Update Text component example to use TextNodeProps

---

demo/package.json
pnpm-lock.yaml

Update demo dependencies to latest version, including Astro to v5.2.5

chore(demo): update Astro to v5.2.5 and other dependencies

---

astro-portabletext/package.json

Updated the `description` to better reflect the purpose of the package

chore(astro-portabletext): update `description` in package.json

---

demo/package.json
pnpm-lock.yaml

Update demo dependencies to latest version, including Astro and astro-portabletext

chore(demo): update Astro to v5.3.0 and other dependencies
